require: rubocop-rspec

AllCops:
  NewCops: enable
  
RSpec/DescribeClass:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/AbcSize:
  Enabled: false



RSpec/NestedGroups:
  Max: 4
